<?php



/**
 * Test class for KrisController.
 * Generated by PHPUnit on 2011-06-27 at 23:13:07.
 */
class KrisControllerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var KrisController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMock('KrisController', array('GetControllerRequest'));
        $this->object->expects($this->once())->method('GetControllerRequest')->will($this->returnCallback(function ($controller, $action, &$error, &$class, &$func)
            {
                if ($controller != 'main')
                {
                    throw new InvalidArgumentException('Invalid controller '.$controller);
                }
                if ($action != 'index')
                {
                    throw new InvalidArgumentException('Invalid action '.$action);
                }
                $func = 'Index';
                $class = new TestControllerClass();
                return true;
            }));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    /**
     * @test
     */
    public function testRoute()
    {
        $_SERVER['REQUEST_URI'] = '/main/index';
        $this->object->Route('');
    }

    /**
     * @test
     * @expectedException InvalidArgumentException
     */
    public function testInvalidAction()
    {
        $_SERVER['REQUEST_URI'] = '/main/foo';
        $this->object->Route('');
    }

    /**
     * @test
     */
    public function testReRoute()
    {
        // Remove the following lines when you implement this test.
        $_SERVER['REQUEST_URI'] = '/main/index';
        $this->object->ReRoute('/main.php', '/main/index');
        $this->object->Route('');

    }
}

class TestControllerClass
{
    public function Index()
    {
        return null;
    }
}

?>
