<?php



/**
 * Test class for KrisController.
 * Generated by PHPUnit on 2011-06-27 at 23:13:07.
 */
class KrisRouterTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var KrisRouter
     */
    protected $krisRouter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->krisRouter = $this->getMock('KrisRouter', array('GetControllerRequest', 'ParseRequest'));


    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @throws InvalidArgumentException
     */
    private function createGetControllerRequest()
    {
        $this->krisRouter->expects($this->once())->method('GetControllerRequest')->will($this->returnCallback(
            function ($controller, $action, &$error, &$class, &$func)
            {
                if ($controller != 'main')
                {
                    throw new InvalidArgumentException('Invalid controller '.$controller);
                }
                if ($action != 'index')
                {
                    throw new InvalidArgumentException('Invalid action '.$action);
                }
                $func = 'Index';
                $class = new TestControllerClass();
                return true;
            }));
    }

    /**
     * @test
     */
    public function testRoute()
    {
        $_SERVER['REQUEST_URI'] = '/main/index';
                
        $this->krisRouter->expects($this->once())->method('ParseRequest')->with('main', 'index', array());
        $this->krisRouter->Route('');
    }


    /**
     * @test
     */
    public function testReRoute()
    {
        // Remove the following lines when you implement this test.
        $_SERVER['REQUEST_URI'] = '/main/index';
        $this->assertEquals('', '');
        $this->krisRouter->ReRoute('/main.php', '/main/index');
        $this->krisRouter->Route('/main.php');

    }
}

/**
 *
 */
class TestControllerClass
{
    /**
     * @return null
     */
    public function Index()
    {
        return null;
    }
}


