<?php



/**
 * Test class for KrisController.
 * Generated by PHPUnit on 2011-06-27 at 23:13:07.
 */
class KrisControllerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var KrisController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new KrisController(KrisConfig::APP_PATH . 'controllers/', KrisConfig::WEB_FOLDER, 'main', 'index');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
