<?php



/**
 * Test class for NumberHelpers.
 * Generated by PHPUnit on 2011-11-06 at 20:47:03.
 */
class NumberHelpersTest extends PHPUnit_Framework_TestCase
{

    /**
     * @test
     */
    public function testBytesToHuman()
    {
        $this->assertEquals('34 Bytes', NumberHelpers::BytesToHuman(34));
        $this->assertEquals('33.20 KB', NumberHelpers::BytesToHuman(34000));
        $this->assertEquals('32.42 MB', NumberHelpers::BytesToHuman(34000000));
        $this->assertEquals('31.66 GB', NumberHelpers::BytesToHuman(34000000000));
    }
}

?>
