<?php


/**
 * Test class for KrisModel.
 * Generated by PHPUnit on 2011-06-27 at 23:07:16.
 */
class KrisCrudModelTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var KrisModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new KrisCrudModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function test
}
?>
