<?php


/**
 * Test class for KrisDBView.
 * Generated by PHPUnit on 2011-06-27 at 23:03:18.
 */
class KrisDBViewTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var KrisDBView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new KrisDBView();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
