<?php


/**
 * Test class for KrisView.
 * Generated by PHPUnit on 2011-06-27 at 23:00:46.
 */
class KrisViewTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var KrisView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new KrisView;
    }

    /**
     * @test
     */
    public function testFetchFromString()
    {
        $res = $this->object->fetchFromString('<test><?= $foo ?></test>', array('foo' => 'bar'));
        $this->assertEquals('<test>bar</test>', $res);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}

