<?php

require_once 'D:\Projects\html\krismvc\framework\lib\plumbing\BucketContainer.php';

/**
 * Test class for bucket_Container.
 * Generated by PHPUnit on 2011-08-01 at 11:58:46.
 */
class bucket_ContainerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var BucketContainer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BucketContainer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @test
     */
    public function testMakeChildContainer()
    {
        $top = new BucketContainer();
        $scope = $top->makeChildContainer();
        $scope->registerImplementation('Zap', 'Foo');
        $bar = $scope->get('Cuux');
        $this->assertInstanceOf('Cuux', $bar);

        $this->setExpectedException('BucketCreationException', 'Undefined class Zap');
        $top->get('Cuux');
    }

    /**
     * @test
     */
    public function testGet()
    {
        $bucket = new BucketContainer();
        $bucket->registerImplementation('Zap', 'Foo');
        $cuux = $bucket->get('Cuux');
        $buux = $bucket->get('Cuux');

        $this->assertTrue($cuux === $buux);
    }

    /**
     * @todo Implement testCreate().
     */
    public function testCreate()
    {
        $bucket = new BucketContainer();
        $bucket->registerImplementation('Zap', 'Foo');
        $cuux = $bucket->create('Cuux');
        $buux = $bucket->create('Cuux');

        $this->assertFalse($cuux === $buux);
    }


}

// Test classes

interface Zap {}

class Foo implements Zap {}

class Bar {
  function __construct(Foo $foo) {}
}

class Cuux {
  function __construct(Zap $zap) {}
}
?>
